# Generated by Django 3.2.4 on 2022-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('emailid', models.CharField(max_length=100, unique=True)),
                ('phonenumber', models.BigIntegerField(max_length=10, unique=True)),
                ('address', models.TextField(max_length=1000)),
                ('dateofbirth', models.DateField()),
            ],
        ),
    ]
